
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'MUL NUM PRT VARINS : VAR "=" EXPINS : "?" VARINS : "!" EXPINS : PRTEXP : EXP \'-\' TERMEXP : EXP \'+\' TERMEXP : TERMTERM : TERM MUL FATORTERM : TERM "/" FATORTERM : FATORFATOR : NUMFATOR : "(" EXP ")"FATOR : VAR'
    
_lr_action_items = {'VAR':([0,3,4,6,12,15,16,17,18,],[2,7,13,13,13,13,13,13,13,]),'?':([0,],[3,]),'!':([0,],[4,]),'PRT':([0,],[5,]),'$end':([1,5,7,8,9,10,11,13,14,20,21,22,23,24,],[0,-4,-2,-3,-7,-10,-11,-13,-1,-5,-6,-8,-9,-12,]),'=':([2,],[6,]),'NUM':([4,6,12,15,16,17,18,],[11,11,11,11,11,11,11,]),'(':([4,6,12,15,16,17,18,],[12,12,12,12,12,12,12,]),'-':([8,9,10,11,13,14,19,20,21,22,23,24,],[15,-7,-10,-11,-13,15,15,-5,-6,-8,-9,-12,]),'+':([8,9,10,11,13,14,19,20,21,22,23,24,],[16,-7,-10,-11,-13,16,16,-5,-6,-8,-9,-12,]),')':([9,10,11,13,19,20,21,22,23,24,],[-7,-10,-11,-13,24,-5,-6,-8,-9,-12,]),'MUL':([9,10,11,13,20,21,22,23,24,],[17,-10,-11,-13,17,17,-8,-9,-12,]),'/':([9,10,11,13,20,21,22,23,24,],[18,-10,-11,-13,18,18,-8,-9,-12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'INS':([0,],[1,]),'EXP':([4,6,12,],[8,14,19,]),'TERM':([4,6,12,15,16,],[9,9,9,20,21,]),'FATOR':([4,6,12,15,16,17,18,],[10,10,10,10,10,22,23,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> INS","S'",1,None,None,None),
  ('INS -> VAR = EXP','INS',3,'p_INSTdVar','calculadora_anasin.py',16),
  ('INS -> ? VAR','INS',2,'p_INSTPRG','calculadora_anasin.py',20),
  ('INS -> ! EXP','INS',2,'p_INSTEXP','calculadora_anasin.py',24),
  ('INS -> PRT','INS',1,'p_INSTPRT','calculadora_anasin.py',28),
  ('EXP -> EXP - TERM','EXP',3,'p_EXPm','calculadora_anasin.py',33),
  ('EXP -> EXP + TERM','EXP',3,'p_EXPM','calculadora_anasin.py',37),
  ('EXP -> TERM','EXP',1,'p_EXPT','calculadora_anasin.py',41),
  ('TERM -> TERM MUL FATOR','TERM',3,'p_TERMV','calculadora_anasin.py',45),
  ('TERM -> TERM / FATOR','TERM',3,'p_TERMD','calculadora_anasin.py',49),
  ('TERM -> FATOR','TERM',1,'p_TERMFATOR','calculadora_anasin.py',53),
  ('FATOR -> NUM','FATOR',1,'p_FATORNUM','calculadora_anasin.py',57),
  ('FATOR -> ( EXP )','FATOR',3,'p_FATOREXP','calculadora_anasin.py',61),
  ('FATOR -> VAR','FATOR',1,'p_FATORVAR','calculadora_anasin.py',65),
]
