
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'FIM NUM PRT VARPROG : PROG INSPROG : INSPROG : FIMINS : VAR "=" EXPINS : "?" VARINS : "!" EXPINS : "*"EXP : EXP \'-\' TERMEXP : EXP \'+\' TERMEXP : TERMTERM : TERM "*" FATORTERM : TERM "/" FATORTERM : FATORFATOR : NUMFATOR : "(" EXP ")"FATOR : VARFATOR : COND "?" EXP ":" EXPCOND : COND "|" CONJCOND : CONJCONJ : CONJ "&" COMPCONJ : COMPCOMP : EXP ">" EXPCOMP : EXP "<" EXP'
    
_lr_action_items = {'FIM':([0,],[3,]),'VAR':([0,1,2,3,5,6,7,8,9,10,11,12,13,14,15,16,20,21,22,23,24,25,26,28,29,30,32,33,36,37,38,42,43,],[4,4,-2,-3,10,16,-7,-1,16,-5,-6,-10,-13,-14,16,-16,-4,16,16,16,16,16,16,16,16,16,-8,-9,-11,-12,-15,16,-17,]),'?':([0,1,2,3,7,8,10,11,12,13,14,16,17,18,19,20,32,33,34,35,36,37,38,40,41,43,],[5,5,-2,-3,-7,-1,-5,-6,-10,-13,-14,-16,28,-19,-21,-4,-8,-9,-22,-23,-11,-12,-15,-18,-20,-17,]),'!':([0,1,2,3,7,8,10,11,12,13,14,16,20,32,33,36,37,38,43,],[6,6,-2,-3,-7,-1,-5,-6,-10,-13,-14,-16,-4,-8,-9,-11,-12,-15,-17,]),'*':([0,1,2,3,7,8,10,11,12,13,14,16,20,32,33,36,37,38,43,],[7,7,-2,-3,-7,-1,-5,-6,25,-13,-14,-16,-4,25,25,-11,-12,-15,-17,]),'$end':([1,2,3,7,8,10,11,12,13,14,16,20,32,33,36,37,38,43,],[0,-2,-3,-7,-1,-5,-6,-10,-13,-14,-16,-4,-8,-9,-11,-12,-15,-17,]),'=':([4,],[9,]),'NUM':([6,9,15,21,22,23,24,25,26,28,29,30,42,],[14,14,14,14,14,14,14,14,14,14,14,14,14,]),'(':([6,9,15,21,22,23,24,25,26,28,29,30,42,],[15,15,15,15,15,15,15,15,15,15,15,15,15,]),'-':([11,12,13,14,16,20,27,31,32,33,34,35,36,37,38,39,43,],[21,-10,-13,-14,-16,21,21,21,-8,-9,21,21,-11,-12,-15,21,21,]),'+':([11,12,13,14,16,20,27,31,32,33,34,35,36,37,38,39,43,],[22,-10,-13,-14,-16,22,22,22,-8,-9,22,22,-11,-12,-15,22,22,]),'>':([11,12,13,14,16,20,27,31,32,33,34,35,36,37,38,39,43,],[23,-10,-13,-14,-16,23,23,23,-8,-9,23,23,-11,-12,-15,23,23,]),'<':([11,12,13,14,16,20,27,31,32,33,34,35,36,37,38,39,43,],[24,-10,-13,-14,-16,24,24,24,-8,-9,24,24,-11,-12,-15,24,24,]),')':([12,13,14,16,27,32,33,36,37,38,43,],[-10,-13,-14,-16,38,-8,-9,-11,-12,-15,-17,]),'&':([12,13,14,16,18,19,32,33,34,35,36,37,38,40,41,43,],[-10,-13,-14,-16,30,-21,-8,-9,-22,-23,-11,-12,-15,30,-20,-17,]),'|':([12,13,14,16,17,18,19,32,33,34,35,36,37,38,40,41,43,],[-10,-13,-14,-16,29,-19,-21,-8,-9,-22,-23,-11,-12,-15,-18,-20,-17,]),':':([12,13,14,16,32,33,36,37,38,39,43,],[-10,-13,-14,-16,-8,-9,-11,-12,-15,42,-17,]),'/':([12,13,14,16,32,33,36,37,38,43,],[26,-13,-14,-16,26,26,-11,-12,-15,-17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'PROG':([0,],[1,]),'INS':([0,1,],[2,8,]),'EXP':([6,9,15,21,22,23,24,25,26,28,29,30,42,],[11,20,27,31,31,34,35,31,31,39,31,31,43,]),'TERM':([6,9,15,21,22,23,24,25,26,28,29,30,42,],[12,12,12,32,33,12,12,12,12,12,12,12,12,]),'FATOR':([6,9,15,21,22,23,24,25,26,28,29,30,42,],[13,13,13,13,13,13,13,36,37,13,13,13,13,]),'COND':([6,9,15,21,22,23,24,25,26,28,29,30,42,],[17,17,17,17,17,17,17,17,17,17,17,17,17,]),'CONJ':([6,9,15,21,22,23,24,25,26,28,29,30,42,],[18,18,18,18,18,18,18,18,18,18,40,18,18,]),'COMP':([6,9,15,21,22,23,24,25,26,28,29,30,42,],[19,19,19,19,19,19,19,19,19,19,19,41,19,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> PROG","S'",1,None,None,None),
  ('PROG -> PROG INS','PROG',2,'p_program','calculadora_anasin_VM.py',57),
  ('PROG -> INS','PROG',1,'p_programIns','calculadora_anasin_VM.py',61),
  ('PROG -> FIM','PROG',1,'p_programFim','calculadora_anasin_VM.py',65),
  ('INS -> VAR = EXP','INS',3,'p_INSdVar','calculadora_anasin_VM.py',69),
  ('INS -> ? VAR','INS',2,'p_INSPRG','calculadora_anasin_VM.py',73),
  ('INS -> ! EXP','INS',2,'p_INSEXP','calculadora_anasin_VM.py',77),
  ('INS -> *','INS',1,'p_INSPRT','calculadora_anasin_VM.py',81),
  ('EXP -> EXP - TERM','EXP',3,'p_EXPm','calculadora_anasin_VM.py',85),
  ('EXP -> EXP + TERM','EXP',3,'p_EXPM','calculadora_anasin_VM.py',89),
  ('EXP -> TERM','EXP',1,'p_EXPT','calculadora_anasin_VM.py',93),
  ('TERM -> TERM * FATOR','TERM',3,'p_TERMV','calculadora_anasin_VM.py',97),
  ('TERM -> TERM / FATOR','TERM',3,'p_TERMD','calculadora_anasin_VM.py',101),
  ('TERM -> FATOR','TERM',1,'p_TERMFATOR','calculadora_anasin_VM.py',105),
  ('FATOR -> NUM','FATOR',1,'p_FATORNUM','calculadora_anasin_VM.py',109),
  ('FATOR -> ( EXP )','FATOR',3,'p_FATOREXP','calculadora_anasin_VM.py',113),
  ('FATOR -> VAR','FATOR',1,'p_FATORVAR','calculadora_anasin_VM.py',117),
  ('FATOR -> COND ? EXP : EXP','FATOR',5,'p_FATORCOND','calculadora_anasin_VM.py',121),
  ('COND -> COND | CONJ','COND',3,'p_CONDCONDJ','calculadora_anasin_VM.py',125),
  ('COND -> CONJ','COND',1,'p_CONDCONJ','calculadora_anasin_VM.py',129),
  ('CONJ -> CONJ & COMP','CONJ',3,'p_CONJCONJP','calculadora_anasin_VM.py',133),
  ('CONJ -> COMP','CONJ',1,'p_CONJCOMP','calculadora_anasin_VM.py',137),
  ('COMP -> EXP > EXP','COMP',3,'p_COMPG','calculadora_anasin_VM.py',141),
  ('COMP -> EXP < EXP','COMP',3,'p_COMPL','calculadora_anasin_VM.py',145),
]
