
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'IF INT READ VAR WHILE WRITEProgram : LInsLIns : LIns InsLIns : InsIns : "(" READ Var ")"Ins : "(" "=" Var Exp ")"Ins : "(" IF "(" Comp ")" Bloco Bloco ")"Ins : "(" WRITE Var ")"Ins : "(" WHILE "(" Comp ")" Bloco ")"Bloco : InsBloco : "(" LIns ")"Exp : "-" Exp TermExp : "+" Exp TermExp : TermTerm : "*" Term FatorTerm : "/" Term FatorTerm : FatorFator : INTFator : "(" Exp ")"Fator : VarVar : VARComp : ">" Exp Exp Comp : "<" Exp Exp'
    
_lr_action_items = {'(':([0,2,3,5,8,10,12,13,17,18,19,21,22,23,24,25,26,27,29,30,31,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,54,56,57,58,],[4,4,-3,-2,14,16,-20,18,-4,18,-19,18,-13,18,18,-16,18,-17,18,18,-7,-5,18,18,18,18,48,18,18,48,-18,-11,-12,-14,-15,4,48,-9,4,-8,-10,-6,]),'$end':([1,2,3,5,17,31,34,56,58,],[0,-1,-3,-2,-4,-7,-5,-8,-6,]),')':([3,5,11,12,15,17,19,20,22,25,27,28,31,32,33,34,43,44,45,46,47,50,51,52,53,54,55,56,57,58,],[-3,-2,17,-20,31,-4,-19,34,-13,-16,-17,39,-7,42,43,-5,-18,-11,-12,-14,-15,-9,-21,-22,56,57,58,-8,-10,-6,]),'READ':([4,48,],[6,6,]),'=':([4,48,],[7,7,]),'IF':([4,48,],[8,8,]),'WRITE':([4,48,],[9,9,]),'WHILE':([4,48,],[10,10,]),'VAR':([6,7,9,12,13,18,19,21,22,23,24,25,26,27,29,30,35,36,37,38,40,41,43,44,45,46,47,],[12,12,12,-20,12,12,-19,12,-13,12,12,-16,12,-17,12,12,12,12,12,12,12,12,-18,-11,-12,-14,-15,]),'-':([12,13,18,19,21,22,23,25,27,29,30,40,41,43,44,45,46,47,],[-20,21,21,-19,21,-13,21,-16,-17,21,21,21,21,-18,-11,-12,-14,-15,]),'+':([12,13,18,19,21,22,23,25,27,29,30,40,41,43,44,45,46,47,],[-20,23,23,-19,23,-13,23,-16,-17,23,23,23,23,-18,-11,-12,-14,-15,]),'*':([12,13,18,19,21,22,23,24,25,26,27,29,30,35,36,40,41,43,44,45,46,47,],[-20,24,24,-19,24,-13,24,24,-16,24,-17,24,24,24,24,24,24,-18,-11,-12,-14,-15,]),'/':([12,13,18,19,21,22,23,24,25,26,27,29,30,35,36,40,41,43,44,45,46,47,],[-20,26,26,-19,26,-13,26,26,-16,26,-17,26,26,26,26,26,26,-18,-11,-12,-14,-15,]),'INT':([12,13,18,19,21,22,23,24,25,26,27,29,30,35,36,37,38,40,41,43,44,45,46,47,],[-20,27,27,-19,27,-13,27,27,-16,27,-17,27,27,27,27,27,27,27,27,-18,-11,-12,-14,-15,]),'>':([14,16,],[29,29,]),'<':([14,16,],[30,30,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Program':([0,],[1,]),'LIns':([0,48,],[2,54,]),'Ins':([0,2,39,42,48,49,54,],[3,5,50,50,3,50,5,]),'Var':([6,7,9,13,18,21,23,24,26,29,30,35,36,37,38,40,41,],[11,13,15,19,19,19,19,19,19,19,19,19,19,19,19,19,19,]),'Exp':([13,18,21,23,29,30,40,41,],[20,33,35,36,40,41,51,52,]),'Term':([13,18,21,23,24,26,29,30,35,36,40,41,],[22,22,22,22,37,38,22,22,44,45,22,22,]),'Fator':([13,18,21,23,24,26,29,30,35,36,37,38,40,41,],[25,25,25,25,25,25,25,25,25,25,46,47,25,25,]),'Comp':([14,16,],[28,32,]),'Bloco':([39,42,49,],[49,53,55,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Program","S'",1,None,None,None),
  ('Program -> LIns','Program',1,'p_prog','sExpp_anasin.py',56),
  ('LIns -> LIns Ins','LIns',2,'p_lins','sExpp_anasin.py',60),
  ('LIns -> Ins','LIns',1,'p_lins1','sExpp_anasin.py',64),
  ('Ins -> ( READ Var )','Ins',4,'p_ins','sExpp_anasin.py',68),
  ('Ins -> ( = Var Exp )','Ins',5,'p_ins1','sExpp_anasin.py',72),
  ('Ins -> ( IF ( Comp ) Bloco Bloco )','Ins',8,'p_ins2','sExpp_anasin.py',76),
  ('Ins -> ( WRITE Var )','Ins',4,'p_ins3','sExpp_anasin.py',80),
  ('Ins -> ( WHILE ( Comp ) Bloco )','Ins',7,'p_ins4','sExpp_anasin.py',84),
  ('Bloco -> Ins','Bloco',1,'p_blobo','sExpp_anasin.py',88),
  ('Bloco -> ( LIns )','Bloco',3,'p_bloco1','sExpp_anasin.py',92),
  ('Exp -> - Exp Term','Exp',3,'p_exp','sExpp_anasin.py',96),
  ('Exp -> + Exp Term','Exp',3,'p_exp1','sExpp_anasin.py',100),
  ('Exp -> Term','Exp',1,'p_exp2','sExpp_anasin.py',104),
  ('Term -> * Term Fator','Term',3,'p_term','sExpp_anasin.py',108),
  ('Term -> / Term Fator','Term',3,'p_term1','sExpp_anasin.py',112),
  ('Term -> Fator','Term',1,'p_term2','sExpp_anasin.py',116),
  ('Fator -> INT','Fator',1,'p_fator','sExpp_anasin.py',120),
  ('Fator -> ( Exp )','Fator',3,'p_fator1','sExpp_anasin.py',124),
  ('Fator -> Var','Fator',1,'p_fator2','sExpp_anasin.py',128),
  ('Var -> VAR','Var',1,'p_var','sExpp_anasin.py',132),
  ('Comp -> > Exp Exp','Comp',3,'p_comp','sExpp_anasin.py',136),
  ('Comp -> < Exp Exp','Comp',3,'p_comp2','sExpp_anasin.py',140),
]
